[package]
name = "nestforge-http"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
axum = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
tower-http = { workspace = true }
nestforge-core = { path = "../nestforge-core" }