[package]
name = "hello-nestforge"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
nestforge = { path = "../../crates/nestforge" }
axum = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }