[package]
name = "nestforge"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
# Public crate re-exports stuff from these internal crates.
nestforge-core = { path = "../nestforge-core" }
nestforge-http = { path = "../nestforge-http" }
tokio = { workspace = true }
anyhow = { workspace = true }