[package]
name = "nestforge"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
nestforge-core = { path = "../nestforge-core" }
nestforge-http = { path = "../nestforge-http" }
nestforge-macros = { path = "../nestforge-macros" }
tokio = { workspace = true }
anyhow = { workspace = true }